CREATE DATABASE `test`;

CREATE TABLE first_form (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
email VARCHAR(50),
reg_date TIMESTAMP
);

CREATE TABLE screen_form (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
form_name VARCHAR(50) NOT NULL,
form_data TEXT,
create_date TIMESTAMP
);

CREATE TABLE second_form (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
subject VARCHAR(50) NOT NULL,
letter VARCHAR(50) NOT NULL,
create_date TIMESTAMP
);